### ISSUE TITLE
SuccessStory / GameActivity buttons only show data if hovered

### ISSUE THREAD

**Issue by shakeyourbunny** [darklinkpower/Stardust#14] opened 2022-02-13 08:08 UTC
### Bug Description

Opening the details page of a game, the buttons for SuccessStory and GameActivity are blank, if not hovered:

not hovered with mouse
![stardust-empty-button-01](https://user-images.githubusercontent.com/5352403/153744429-fcdfb110-43a0-4925-8002-1cbcd840afa5.PNG)

hovered with mouse
![stardust-empty-button-02](https://user-images.githubusercontent.com/5352403/153744474-3e4c0098-5369-48be-99b7-f566aab17e49.PNG)

Is this by design or a bug? I'd like to see this without having to hover on it. On other themes, this works without issues.

### To Reproduce

- Install Stardust theme.
- install Success Story
- install Game Activity
- hit F9 -> Extension settings -> Generic -> SuccessStory -> Appearance -> check "Display the plugin button" -> check "with details"
- hit F9 -> Extension settings -> Generic -> GameActivity -> Appearance -> check "Display the plugin button" -> check "with details"

**Comment by darklinkpower** [comment] 2022-02-13 12:59
This is caused by the plugin hardcoding/forcing the brush used by the text. See https://github.com/Lacro59/playnite-gameactivity-plugin/blob/master/source/Controls/PluginButton.xaml#L47 and https://github.com/Lacro59/playnite-gameactivity-plugin/blob/master/source/Controls/PluginButton.xaml#L62

The GlyphBrush color is used in the theme for the background in buttons (Can also be seen in other buttons, like in the game edit window for example), which means that both the text and button will use the same color and the text will be "invisible" as a result. 

I don't think it's a good idea to force things like colors in plugins controls because it's not possible to know what styling will themes use and can cause issues like this. As for the fix, this is something that has to be fixed plugin's side by changing the styling of the control to not force specific brushes that will possibly not work in some themes.

One idea to fix this in the plugin is to change the text opacity slightly instead of colors. In any case, I suggest to open an issue in the plugins repositories.

**Comment by darklinkpower** [comment] 2022-02-13 13:16
By the way, seeing as you use the theme, I wanted to ask what do you think of the changes in the latest update. I usually don't receive feedback so I just do what I think works best and considering I made significant changes to the theme, It would be appreciated if you have any feedback about them.

**Comment by shakeyourbunny** [comment] 2022-02-13 13:49
> As for the fix, this is something that has to be fixed plugin's side by changing the styling of the control to not force specific brushes that will possibly not work in some themes.
I will open 2 issues on the plugin's side, thank you for your investigation.

> I wanted to ask what do you think of the changes in the latest update.
I really like the changes for Stardust, especially it is more colorful and I have the feeling that much of the unnecessary whitespace and monochromatic design is gone which held me back. I regularily swap between Felix' DuplicateHider Reference Theme and StarDust, although I lean more to the Stardust theme.

The small icons in the detail view are great.

The buttons on the far left side (Library, Statistics, plugin ones like SuccessStory, GameActivity) are a bit too dim imho.

The only things I miss on Stardust is the extended play button (that pops up if the mouse enters the playbutton when a game with hidden copys is selected) and that the top icon row with the (too small) search field is not on the left (maybe make it configurable to set it to left/middle/right, default middle)?

**Comment by shakeyourbunny** [comment] 2022-02-13 13:52
Oh, and implementing https://github.com/darklinkpower/Stardust/issues/13 would be great too.

**Comment by darklinkpower** [comment] 2022-02-14 23:38
Closing

I've implemented #13  and increased the base opacity of sidebar items.

Regarding the Play button thing, please open an issue where you further explain what it is since I'm not sure what it is. Regarding the search field I don't think it's possible because it will conflict with the other elements that dock left or right in the panel, like plugin items and other buttons but you can open an issue to be investigated

**Closed by darklinkpower** 2022-02-14 23:38 UTC
Labels: bug
